config/routes.rb
Refinery::Core::Engine.routes.draw do
  namespace :search, path: Refinery::Search.page_url do
    root to: 'search#show'
  end
end

app/models/refinery/search/search_engine.rb
module Refinery
  module Search
    class SearchEngine

      # Perform search over the specified models
      def self.search(query)
        results = []

        Refinery::Search.config.enable_for.each do |model|
          model = model.safe_constantize

          if model.respond_to?(:refinery_search_scope)
            results << model.refinery_search_scope.with_query(query)
          else
            results << model.with_query(query)
          end
        end if query.present?

        results.flatten.uniq
      end

    end
  end
end

app/models/search_engine.rb
class SearchEngine

  # How many results should we show per page
  RESULTS_LIMIT = 10

  # Perform search over the specified models
  def self.search(query, page = 1)
    results = []

    Refinery.searchable_models.each do |model|
      results << model.limit(RESULTS_LIMIT).with_query(query)
    end if query.present?

    results.flatten[0..(RESULTS_LIMIT - 1)]
  end

end

app/controllers/refinery/search/search_controller.rb
require 'will_paginate/array'

module Refinery
  module Search
    class SearchController < ::ApplicationController

      before_action :find_page

      def show
        @results = Refinery::Search::SearchEngine.search(params[:query].try(:to_ascii))
        @results = @results.paginate(page: params[:page], per_page: Refinery::Search.results_per_page)
      end

      protected

        def find_page
          @page = Refinery::Page.find_by(link_url: Refinery::Search.page_url)
        end

    end
  end
end

app/helpers/refinery/search/search_helper.rb
module Refinery
  module Search
    module SearchHelper

      def result_title(result)
        Refinery.deprecate("Refinery::Search::SearchHelper#result_title", when: "3.1", replacement: "result_mark")
        result_mark(result.title)
      end

      def result_mark(field)
        field.gsub /(#{Regexp.escape(params[:query])})/i, '<mark>\1</mark>'
      end

      def result_type(result)
        if result.class.method_defined?(:friendly_search_name)
          result.friendly_search_name
        else
          result.class.to_s.titleize.split("/").last
        end
      end

      # this is where you register your result URLs based on the
      # type of result we're dealing with
      def result_url(result)
        if result.respond_to? :url
          refinery.url_for result.url
        else
          refinery.url_for refinery.send(Refinery.route_for_model(result.class, admin: false), result)
        end
      end

    end
  end
end

app/views/refinery/search/search/show.html.erb
<% content_for :body_content_title do %>
  <% if params[:query].present? %>
    <%= t('.search_results_for', what: params[:query]) %>
  <% else %>
    <%= t('.no_results') %>
  <% end %>
<% end %>

<% content_for :body do %>
  <% if params[:query].present? %>
    <% if @results.present? %>
      <ul id="search_results">
        <% @results.each do |result| %>
          <li>
            <span class='result_type'>
              <%= result_type result %>
            </span>
            <%= link_to result_mark(result.title).html_safe, result_url(result) %>
          </li>
        <% end %>
      </ul>
      <%= will_paginate @results %>
    <% else %>
      <%= t('.no_results') %>
    <% end %>
  <% else %>
    <%= t('.no_results') %>
  <% end %>
<% end %>

<%= render "/refinery/content_page" %>

app/views/refinery/shared/_search.html.erb
<%= form_tag refinery.search_root_path, method: 'get' do %>
  <%= label_tag 'query', t('.search_label') %>
  <%= text_field_tag :query, {}, {type: "search", placeholder: t(".search_site_for"), value: (params[:query] if params[:query])} %>
  <%= submit_tag t(".go") %>
<% end %>

app/views/search/show.html.erb
<% content_for :body_content_title do %>
  Search Results for '<%=h params[:query] %>'
<% end %>

<% content_for :body_content_left do %>
  <ul id="search_results">
    <% @results.each do |result| %>
      <li>
        <span class='result_type'>
          <%= result.class.to_s.titleize %>
        </span>
        <%= link_to raw(result.title.gsub(/(#{Regexp.escape(params[:query])})/i, '<mark>\1</mark>')), result_url(result) %>
      </li>
    <% end %>
  </ul>

<% end %>

<%= render :partial => "/shared/content_page" %>
<% content_for :stylesheets do %>
  <style type='text/css'>
    #search_results {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    #search_results li {
      border-bottom: 1px solid #CCC;
    }

    #search_results li span.result_type {
      float: right;
      color: #CCC;
    }
  </style>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag search_url do -%>
  <%= text_field_tag :query, {}, {:type => "search",
                     :placeholder => "Search site for...", 
                     :value => (params[:query] if params[:query])} %>
  <%= submit_tag 'Go' %>
<% end %>